export const course = [
  {
    id: 'foundation',
    number: '01',
    title: 'The foundation',
    detail: 'Make harmony move',
    lessons: [
      {
        id: 'make-one-chord-move',
        title: 'Make one chord',
        accent: 'feel like music.',
        intro: 'You already know the notes. Now give them motion. A few dependable left-hand shapes can turn a chord chart into an accompaniment.',
        idea: 'Harmony + motion = accompaniment',
        duration: 10,
        patternIds: ['roots', 'fifths', 'broken', 'rolling'],
        defaultPattern: 'broken',
        defaultKey: 'C',
        tempo: 72,
        pickerTitle: 'Choose a formula',
        pickerCopy: 'One chord progression. Four completely different moods.',
        studioTitle: 'Hear it. Then play it.',
        handHint: 'Keep your wrist soft and let your hand move as one shape.',
        listen: {
          title: 'The bass tells the story.',
          body: 'Even when the right hand rests, these four roots make the progression recognizable. Hum a melody while the left hand loops.',
        },
        tip: {
          title: 'Move early, land softly.',
          body: 'As soon as beat four sounds, let your eyes and wrist prepare for the next chord. Accuracy comes from calm movement.',
        },
        challenge: ['Loop the progression without stopping.', 'Keep every beat equally spaced.', 'Hum any melody above the left hand.'],
      },
      {
        id: 'hear-chords-by-number',
        title: 'Hear chords',
        accent: 'by number.',
        intro: 'Chord names change with the key, but their jobs stay the same. Learn the sound of I–vi–IV–V and you can recognize it anywhere.',
        idea: 'Numbers describe a chord’s job, not its spelling',
        duration: 9,
        patternIds: ['roots', 'fifths'],
        defaultPattern: 'roots',
        defaultKey: 'G',
        tempo: 68,
        pickerTitle: 'Strip it back',
        pickerCopy: 'Simple patterns leave room to hear where each chord wants to go.',
        studioTitle: 'Change the key, keep the story.',
        handHint: 'Say each number aloud as its root lands: one, six, four, five.',
        listen: {
          title: 'I feels like home.',
          body: 'The vi chord turns inward, IV opens the sound, and V creates a gentle pull back toward I. Listen for those roles in every key.',
        },
        tip: {
          title: 'Name the function first.',
          body: 'Read the Roman numeral before the chord letter. Thinking “four” instead of “F” makes transposing much easier later.',
        },
        challenge: ['Play the roots in C major.', 'Switch to G major without changing the numbers.', 'Look away and identify when I returns.'],
      },
      {
        id: 'change-without-the-bump',
        title: 'Change chords',
        accent: 'without the bump.',
        intro: 'A beautiful accompaniment is connected by what happens between chords. Prepare the next shape before the listener can hear the move.',
        idea: 'Release, travel, arrive—inside one steady pulse',
        duration: 11,
        patternIds: ['fifths', 'broken'],
        defaultPattern: 'fifths',
        defaultKey: 'F',
        tempo: 60,
        pickerTitle: 'Choose a clear texture',
        pickerCopy: 'Space between notes makes every hand movement easy to notice and refine.',
        studioTitle: 'Practice the space between.',
        handHint: 'Let the final note go, travel immediately, then arrive with relaxed fingers.',
        listen: {
          title: 'Silence can stay in time.',
          body: 'A tiny breath before the next chord sounds intentional when the pulse continues. Rushing the arrival sounds less musical than a clean release.',
        },
        tip: {
          title: 'Look one chord ahead.',
          body: 'Your eyes should find the next root while your hand finishes the current pattern. The hand follows where the eyes have already gone.',
        },
        challenge: ['Practice only the last note and next root.', 'Loop at 60 BPM with no extra pauses.', 'Raise the tempo only after three clean loops.'],
      },
    ],
  },
  {
    id: 'color',
    number: '02',
    title: 'Add color',
    detail: 'Depth without clutter',
    lessons: [
      {
        id: 'use-the-third-on-purpose',
        title: 'Use the third',
        accent: 'on purpose.',
        intro: 'The third is the note that tells us whether a chord feels bright or shaded. Bring it forward when you want the harmony to speak clearly.',
        idea: 'The root names the chord; the third reveals its mood',
        duration: 10,
        patternIds: ['broken', 'alberti'],
        defaultPattern: 'broken',
        defaultKey: 'C',
        tempo: 66,
        pickerTitle: 'Put the third in motion',
        pickerCopy: 'Each formula places the middle note where your ear can notice its color.',
        studioTitle: 'Hear major and minor turn.',
        handHint: 'Give the third a little less weight than the root—present, but never poked.',
        listen: {
          title: 'C–E feels open; A–C feels tender.',
          body: 'The interval from root to third changes between major and minor chords. Notice the emotional shift without needing to name every note.',
        },
        tip: {
          title: 'Balance from the bottom.',
          body: 'Let the root be the warmest note, then play the third and fifth more lightly. The chord stays clear without becoming harsh.',
        },
        challenge: ['Sing each third before playing it.', 'Make major and minor sound distinct.', 'Keep the root louder than the upper notes.'],
      },
      {
        id: 'borrow-a-little-air',
        title: 'Borrow',
        accent: 'a little air.',
        intro: 'You do not need more notes to create color. Wider spacing lets familiar triads breathe and keeps the middle of the piano open for melody.',
        idea: 'Spacing changes the color before harmony changes',
        duration: 8,
        patternIds: ['fifths', 'alberti'],
        defaultPattern: 'fifths',
        defaultKey: 'D',
        tempo: 64,
        pickerTitle: 'Open the middle',
        pickerCopy: 'A missing or delayed third can sound spacious, modern, and surprisingly complete.',
        studioTitle: 'Let the chord breathe.',
        handHint: 'Imagine the notes hanging from your fingertips; avoid stretching or locking the thumb.',
        listen: {
          title: 'The fifth has no major or minor label.',
          body: 'Root and fifth create an open frame. When the third arrives later, the listener hears its color more strongly.',
        },
        tip: {
          title: 'Leave room for the song.',
          body: 'If the melody is busy, simplify the left hand. Space is not an unfinished arrangement—it is part of the arrangement.',
        },
        challenge: ['Play one loop with only root and fifth.', 'Add the third on the second half.', 'Compare which version leaves more space to sing.'],
      },
      {
        id: 'connect-with-common-tones',
        title: 'Connect with',
        accent: 'common tones.',
        intro: 'Neighboring chords often share a note. Hearing that thread helps the accompaniment feel connected even while the bass moves underneath it.',
        idea: 'Hold what belongs; move only what must move',
        duration: 12,
        patternIds: ['broken', 'rolling'],
        defaultPattern: 'broken',
        defaultKey: 'F',
        tempo: 58,
        pickerTitle: 'Trace the inner voice',
        pickerCopy: 'Slower flowing patterns make shared notes and stepwise motion easier to hear.',
        studioTitle: 'Listen through the chord change.',
        handHint: 'Keep the arm quiet and let small finger changes do the connecting work.',
        listen: {
          title: 'Some notes barely need to move.',
          body: 'F and Am share two tones; C and Am do too. Listen for pitches that remain while the chord name changes around them.',
        },
        tip: {
          title: 'Choose the nearest note.',
          body: 'When two versions of a chord are available, favor the one that asks your upper fingers to travel the shortest distance.',
        },
        challenge: ['Find one shared note between neighboring chords.', 'Play that note alone through the change.', 'Restore the pattern without losing the inner thread.'],
      },
    ],
  },
  {
    id: 'motion',
    number: '03',
    title: 'Create motion',
    detail: 'Rhythm with intention',
    lessons: [
      {
        id: 'choose-the-right-pulse',
        title: 'Choose the',
        accent: 'right pulse.',
        intro: 'Rhythm tells the listener how to inhabit a song. The same chords can feel like a ballad, a pop groove, or a waltz before the melody even begins.',
        idea: 'Style begins with where the accompaniment breathes',
        duration: 12,
        patternIds: ['roots', 'alberti', 'waltz'],
        defaultPattern: 'waltz',
        defaultKey: 'G',
        tempo: 78,
        pickerTitle: 'Change the feel',
        pickerCopy: 'Compare steady quarters, a turning pulse, and three beats to the bar.',
        studioTitle: 'Let the meter lead.',
        handHint: 'Let beat one settle, then allow the remaining beats to answer more lightly.',
        listen: {
          title: 'Strong does not mean loud.',
          body: 'The first beat feels strong because it arrives and grounds the bar. A subtle weight change is enough to reveal the meter.',
        },
        tip: {
          title: 'Count before you play.',
          body: 'Say one full bar out loud, then enter without changing speed. The count-in puts rhythm in the body before notes distract you.',
        },
        challenge: ['Count four beats over Root notes.', 'Switch to the Waltz pattern and count three.', 'Keep beat one clear without accenting harshly.'],
      },
      {
        id: 'build-and-release-energy',
        title: 'Build and release',
        accent: 'energy.',
        intro: 'Motion becomes expressive when it changes. A verse can leave space; a chorus can flow; a final line can return to stillness.',
        idea: 'More motion creates energy; less motion creates room',
        duration: 10,
        patternIds: ['roots', 'broken', 'rolling'],
        defaultPattern: 'rolling',
        defaultKey: 'C',
        tempo: 74,
        pickerTitle: 'Design an energy curve',
        pickerCopy: 'Treat each formula as a different level of intensity, not a permanent choice.',
        studioTitle: 'Grow without speeding up.',
        handHint: 'As notes become faster, make the movement smaller and the touch lighter.',
        listen: {
          title: 'Intensity and tempo are different.',
          body: 'The rolling pattern feels more active at the same BPM. Keep the pulse fixed so the arrangement grows without rushing.',
        },
        tip: {
          title: 'Change one thing at a time.',
          body: 'First add notes, then add volume if the music still needs it. Layering every kind of intensity at once leaves nowhere to grow.',
        },
        challenge: ['Play Root notes for one loop.', 'Move to Broken chord, then Rolling eighths.', 'Return to Root notes without changing tempo.'],
      },
      {
        id: 'shape-with-touch',
        title: 'Shape a phrase',
        accent: 'with touch.',
        intro: 'A pattern should never sound like a machine. Small changes in weight, length, and direction turn repetition into a phrase with a destination.',
        idea: 'Repeat the notes; vary the intention',
        duration: 11,
        patternIds: ['broken', 'rolling', 'waltz'],
        defaultPattern: 'broken',
        defaultKey: 'D',
        tempo: 62,
        pickerTitle: 'Choose your canvas',
        pickerCopy: 'Any repeating figure can carry a long rise and a gentle release.',
        studioTitle: 'Play toward a destination.',
        handHint: 'Shape from the arm, not by pressing individual fingers harder.',
        listen: {
          title: 'Every loop needs a high point.',
          body: 'Aim the phrase toward the V chord, then let I feel like an exhale. Direction makes repetition feel inevitable rather than static.',
        },
        tip: {
          title: 'Record one quiet loop.',
          body: 'Listening back reveals bumps your hands may not notice. Ask only: where did the phrase grow, and where did it settle?',
        },
        challenge: ['Begin as softly as you can control.', 'Grow gradually toward the V chord.', 'Let the return to I feel lighter, not slower.'],
      },
    ],
  },
  {
    id: 'song',
    number: '04',
    title: 'Shape a song',
    detail: 'From intro to ending',
    lessons: [
      {
        id: 'support-the-melody',
        title: 'Support',
        accent: 'the melody.',
        intro: 'The left hand is successful when the melody feels more natural above it. Listen for long notes, lyric pauses, and places where harmony should stay out of the way.',
        idea: 'Accompaniment frames the melody; it never competes',
        duration: 12,
        patternIds: ['roots', 'fifths', 'broken'],
        defaultPattern: 'roots',
        defaultKey: 'F',
        tempo: 68,
        pickerTitle: 'Make room first',
        pickerCopy: 'Begin with the smallest useful texture and add motion only where the melody welcomes it.',
        studioTitle: 'Sing above the pattern.',
        handHint: 'If you cannot comfortably sing over it, the left hand is probably too loud or busy.',
        listen: {
          title: 'Long melody notes invite motion.',
          body: 'When the voice holds, a broken chord can gently fill the space. When lyrics move quickly, roots or fifths often support them better.',
        },
        tip: {
          title: 'Practice the melody out loud.',
          body: 'Your voice instantly exposes whether the accompaniment breathes in the right places. Musical balance matters more than vocal polish.',
        },
        challenge: ['Hum over Root notes.', 'Use Broken chord only under long tones.', 'Return to Roots when the imaginary lyric gets busy.'],
      },
      {
        id: 'arrange-a-complete-arc',
        title: 'Arrange a',
        accent: 'complete arc.',
        intro: 'A whole-song arrangement needs contrast. Plan where the texture enters, grows, drops away, and returns before decorating individual chords.',
        idea: 'A song is a journey through levels of energy',
        duration: 14,
        patternIds: ['roots', 'fifths', 'broken', 'rolling', 'waltz'],
        defaultPattern: 'broken',
        defaultKey: 'G',
        tempo: 72,
        pickerTitle: 'Assign each section a role',
        pickerCopy: 'Use texture to separate intro, verse, chorus, and final line while keeping one musical identity.',
        studioTitle: 'Rehearse the transitions.',
        handHint: 'Decide the next texture before the section changes; confidence is part of the sound.',
        listen: {
          title: 'Contrast makes simple material feel new.',
          body: 'A familiar progression can carry an entire song when density changes. The ear notices the new frame, not the repeated chords.',
        },
        tip: {
          title: 'Write a one-line map.',
          body: 'Try: intro—fifths, verse—roots, chorus—broken, last line—roots. A clear map frees you to listen while playing.',
        },
        challenge: ['Choose three formulas for three sections.', 'Change texture without breaking the pulse.', 'Repeat the arc and make the final section calmer.'],
      },
      {
        id: 'begin-and-end-beautifully',
        title: 'Begin and end',
        accent: 'beautifully.',
        intro: 'An arrangement feels finished when it knows how to enter and leave. A short preview of the pattern creates an intro; a deliberate slowdown and final home chord create an ending.',
        idea: 'Frame the song with intention',
        duration: 15,
        patternIds: ['roots', 'fifths', 'broken', 'rolling', 'alberti', 'waltz'],
        defaultPattern: 'alberti',
        defaultKey: 'C',
        tempo: 66,
        pickerTitle: 'Choose your signature sound',
        pickerCopy: 'This final practice brings every formula together. Pick the texture that sounds most like you.',
        studioTitle: 'Play your final arrangement.',
        handHint: 'At the end, breathe with the last chord and release only after its sound has fully settled.',
        listen: {
          title: 'The first bar makes a promise.',
          body: 'An intro quietly establishes key, tempo, and character. Keep it short enough that the melody still feels like the reason we are here.',
        },
        tip: {
          title: 'End on purpose, not by running out.',
          body: 'Broaden the final bar, land on I, and keep your hands still while it rings. Silence completes the cadence.',
        },
        challenge: ['Play a two-bar intro.', 'Build through two contrasting textures.', 'Broaden the final bar and let the I chord ring.'],
      },
    ],
  },
]

export const lessons = course.flatMap((chapter, chapterIndex) =>
  chapter.lessons.map((lesson, lessonIndex) => ({
    ...lesson,
    chapterId: chapter.id,
    chapterNumber: chapter.number,
    chapterTitle: chapter.title,
    lessonNumber: String(lessonIndex + 1).padStart(2, '0'),
    courseNumber: String(chapterIndex * 3 + lessonIndex + 1).padStart(2, '0'),
  })),
)
