import { odeToJoy } from './odeLesson.js'
import { preludeInC } from './preludeLesson.js'

const catalog = [
  ['Minuet in G Major', 'Christian Petzold', 'Baroque dance', 'Beginner'],
  ['Musette in D Major', 'Johann Sebastian Bach', 'Baroque dance', 'Beginner'],
  ['Jesu, Joy of Man’s Desiring', 'Johann Sebastian Bach', 'Chorale', 'Intermediate'],
  ['Air on the G String', 'Johann Sebastian Bach', 'Orchestral air', 'Intermediate'],
  ['Sheep May Safely Graze', 'Johann Sebastian Bach', 'Pastoral aria', 'Intermediate'],
  ['Minuet in G Minor', 'Christian Petzold', 'Baroque dance', 'Beginner'],
  ['Solfeggietto', 'C. P. E. Bach', 'Keyboard study', 'Intermediate'],
  ['Sonata in C Major, K. 545', 'Wolfgang Amadeus Mozart', 'Classical sonata', 'Intermediate'],
  ['Rondo alla Turca', 'Wolfgang Amadeus Mozart', 'Classical rondo', 'Advanced'],
  ['Eine kleine Nachtmusik', 'Wolfgang Amadeus Mozart', 'Serenade', 'Intermediate'],
  ['Ah vous dirai-je, Maman', 'Wolfgang Amadeus Mozart', 'Theme and variations', 'Intermediate'],
  ['Für Elise', 'Ludwig van Beethoven', 'Bagatelle', 'Intermediate'],
  ['Moonlight Sonata', 'Ludwig van Beethoven', 'Piano sonata', 'Intermediate'],
  ['Pathétique Sonata', 'Ludwig van Beethoven', 'Piano sonata', 'Advanced'],
  ['Minuet in G Major, WoO 10', 'Ludwig van Beethoven', 'Classical dance', 'Beginner'],
  ['Ecossaise in G Major', 'Ludwig van Beethoven', 'Country dance', 'Beginner'],
  ['Symphony No. 5 Theme', 'Ludwig van Beethoven', 'Symphonic theme', 'Beginner'],
  ['The Blue Danube', 'Johann Strauss II', 'Waltz', 'Intermediate'],
  ['Radetzky March', 'Johann Strauss I', 'March', 'Intermediate'],
  ['Brahms’ Lullaby', 'Johannes Brahms', 'Lullaby', 'Beginner'],
  ['Hungarian Dance No. 5', 'Johannes Brahms', 'Romantic dance', 'Advanced'],
  ['Waltz in A-flat Major', 'Johannes Brahms', 'Waltz', 'Intermediate'],
  ['Spring Song', 'Felix Mendelssohn', 'Song without words', 'Intermediate'],
  ['Wedding March', 'Felix Mendelssohn', 'Incidental music', 'Intermediate'],
  ['Traumerei', 'Robert Schumann', 'Character piece', 'Intermediate'],
  ['The Happy Farmer', 'Robert Schumann', 'Character piece', 'Beginner'],
  ['Melody, Op. 68 No. 1', 'Robert Schumann', 'Character piece', 'Beginner'],
  ['Clair de lune', 'Claude Debussy', 'Impressionist piece', 'Advanced'],
  ['The Little Shepherd', 'Claude Debussy', 'Character piece', 'Intermediate'],
  ['Arabesque No. 1', 'Claude Debussy', 'Impressionist piece', 'Advanced'],
  ['Gymnopédie No. 1', 'Erik Satie', 'Impressionist miniature', 'Intermediate'],
  ['Gnossienne No. 1', 'Erik Satie', 'Piano miniature', 'Intermediate'],
  ['The Entertainer', 'Scott Joplin', 'Ragtime', 'Intermediate'],
  ['Maple Leaf Rag', 'Scott Joplin', 'Ragtime', 'Advanced'],
  ['The Easy Winners', 'Scott Joplin', 'Ragtime', 'Intermediate'],
  ['Morning Mood', 'Edvard Grieg', 'Orchestral miniature', 'Beginner'],
  ['In the Hall of the Mountain King', 'Edvard Grieg', 'Orchestral theme', 'Intermediate'],
  ['Arietta, Op. 12 No. 1', 'Edvard Grieg', 'Lyric piece', 'Intermediate'],
  ['New World Symphony Theme', 'Antonín Dvořák', 'Symphonic theme', 'Beginner'],
  ['Humoresque No. 7', 'Antonín Dvořák', 'Character piece', 'Intermediate'],
  ['Swan Lake Theme', 'Pyotr Ilyich Tchaikovsky', 'Ballet theme', 'Intermediate'],
  ['Dance of the Sugar Plum Fairy', 'Pyotr Ilyich Tchaikovsky', 'Ballet dance', 'Intermediate'],
  ['Morning Prayer', 'Pyotr Ilyich Tchaikovsky', 'Children’s album', 'Beginner'],
  ['Waltz of the Flowers', 'Pyotr Ilyich Tchaikovsky', 'Ballet waltz', 'Intermediate'],
  ['Prelude in E Minor', 'Frédéric Chopin', 'Romantic prelude', 'Intermediate'],
  ['Waltz in A Minor', 'Frédéric Chopin', 'Romantic waltz', 'Intermediate'],
  ['Nocturne in E-flat Major', 'Frédéric Chopin', 'Nocturne', 'Advanced'],
]

const catalogPieces = catalog.map(([title, composer, form, level], index) => ({
  number: String(index === 0 ? 3 : index + 4).padStart(2, '0'),
  title,
  composer,
  description: form,
  meta: [level, 'Catalog'],
}))

export const libraryPieces = [
  {
    number: '01',
    title: 'Canon in D',
    composer: 'Johann Pachelbel',
    description: 'Build a flowing texture from an eight-note bass, chords, rhythm, and melody.',
    meta: ['D major', 'Catalog'],
  },
  {
    route: '#/ode-to-joy',
    number: '02',
    title: odeToJoy.title,
    composer: odeToJoy.composer,
    description: 'Discover how a stepwise melody and two dependable chords create an anthem.',
    meta: [odeToJoy.key, `${odeToJoy.steps.length} layers`, `${odeToJoy.tempo} bpm`],
    playId: 'ode-full',
    events: odeToJoy.events,
    tempo: odeToJoy.tempo,
  },
  {
    route: '#/prelude-in-c', number: '04', title: preludeInC.title, composer: preludeInC.composer,
    description: 'Unfold Bach’s complete harmonic journey through one endlessly flowing pattern.',
    meta: [preludeInC.key, `${preludeInC.steps.length} layers`, `${preludeInC.tempo} bpm`],
    playId: 'prelude-full', events: preludeInC.events, tempo: preludeInC.tempo,
  },
  ...catalogPieces,
].sort((a, b) => Number(a.number) - Number(b.number))
